print('Exercises 1.8')
print(1,'.',sep='')
print('*******************')
print('*******************')
print('*******************')
print('*******************')
print(2,'.',sep='')
print('*******************')
print('*                 *')
print('*                 *')
print('*******************')
print(3,'.',sep='')
print('*')
print('**')
print('***')
print('****')
print(4,'.',sep='')
print('result =',(512-282)/(47*48+5))
print(5,'.',sep='')
temp = eval(input('Enter a number: '))
print('The square of',temp,'is',temp*temp)
print(6,'.',sep='')
temp = eval(input('Enter a number: '))
print(temp,temp*2,temp*3,temp*4,temp*5,sep='---')
print(7,'.',sep='')
temp = eval(input('Enter weight in Kg: '))
print('The weight in Pound is',temp*2.2)
print(8,'.',sep='')
temp1 = eval(input('Enter first number: '))
temp2 = eval(input('Enter second number: '))
temp3 = eval(input('Enter third number: '))
total = temp1+temp2+temp3
average = total/3
print('The sum is',total,end=". ")
print('The average is',average)
print(9,'.',sep='')
meal = eval(input('Enter the meal price: '))
rate = eval(input('Enter the tip rate: '))
tip = meal*(rate/100)
print('Tip amount will be',tip,'and the total bill will be',meal+tip,'.')

print('finished')